### ISSUE TITLE
Add sort key flag to topic>

### ISSUE THREAD

**Issue by bailantilles** [dokufreaks/plugin-tag#145]
Ultimately, I'd like to sort the output of the topic> function independently of the global configuration option, specifically sorting the output on 1 page by reverse modified date.

**Comment by LarsGit223** [comment]
Independent sorting is possible, e.g.:

```{{topic>tag1&sort}}``` or ```{{topic>tag1&rsort}}```

That sort/rsorts the resulting list, no matter what value the global config setting has got.  This was fixed in b7fc64c7f61afe52d4fa5fb090d9e41293f769d8, you have to install the latest version to make it work. A simple re-install should do it.

I think sorting by date is currently not possible.

**Comment by Klap-in** [comment]
After merging of https://github.com/dokufreaks/plugin-pagelist/pull/153, `&sortby=date&rsort` can do the job. But you can already use the tag plugin specific tags `&sortkey=mdate&sortorder=descending`.
