### ISSUE TITLE
Tagging included pages produces non-working tags

### ISSUE THREAD

**Issue by processo** [dokufreaks/plugin-tag#150]
#### How to reproduce the problem
1. create page A that includes page B
`{{page>tagtest2}}`
![tagtest 1](https://cloud.githubusercontent.com/assets/5299789/9830259/4348057a-5928-11e5-9c48-d889bb16c043.png)
2. go to page A and press the Edit button of the included page
3. in the editor add a tag to page B and press Save
`{{tag>test}}`
4. when returned to page A, click on the newly added tag
![tagtest 2](https://cloud.githubusercontent.com/assets/5299789/9830265/5cdf2db0-5928-11e5-9682-35fac9560d81.png)
5. the pagelist of the tag will be empty + the tag will not work with inclusion filters

#### Weird "solution"
1. go to page B directly
2. click on the tag to make the system aware of its existence (now page B shows up in the tag pagelist)
3. go to page A and click on the included page B's tag
4. everything work well

**Comment by michitux** [comment]
The problem here is that the information about page B needs to be updated in the search index which is only done when the page is visited. When you edit B through that button in page A, you are directly redirected to A again after editing and thus the search index information about B is not updated. This is not just an issue with tags, but actually with the whole content of the page, i.e. newly added words also won't be available in the regular search. I fear there is nothing the tag plugin can do concerning this problem. The include plugin would be a more appropriate place for a fix. A possible solution might be to update the search index directly before the redirect happens.
