### ISSUE TITLE
Let topic list pages that aren't visible to the user

### ISSUE THREAD

**Issue by iainhallam** [dokufreaks/plugin-tag#187]
I'm using tags to categorise songs on our choir website, for things like genre and decade, but I also have a tag for "Current repertoire". All the song pages are in a namespace that is only visible to singers using ACLs.

I'd like to present a public list of our songs using the `{{topic ... &simplelist}}` form, but when I view the site in an incognito browser, the list is empty. It's fine when I'm logged in as a user who can see the song pages.

Is there a way I could get the tag plugin to present a list of the pages without links (since public users can't click on them) to show what our repertoire is?

**Comment by Klap-in** [comment]
This does not exist. At the moment the tag plugin quite strict with checking ACL. 

This needs something, e.g. a special syntax that does allow listing tagged pages, that are not visible for the user, or an extra syntax that needs enabling in the configuration. However, because it circumvents the ACL check, somewhere it should be explicit be allowed. 

Maybe by making this a separate plugin. If it is installed by the admin, you believes it is fine that each user can list pages that are ACL protected, just because these are tagged.

**Comment by Klap-in** [comment]
I consider this as too complicated to create, therefore, I'm closing this request.
